import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

const __dirname = dirname(fileURLToPath(import.meta.url));
const scriptPath = join(__dirname, "..", "..", "scripts", "build-dashboard-ui.mjs");

// Generated Flutter state that a previous release leaves behind under
// flutter_dashboard. A warm `.dart_tool/flutter_build/<hash>/` cache hands the
// next `flutter build web` a web_plugin_registrant.dart generated for the old
// plugin set, so a release that adds web plugins ships a dashboard that never
// registers them (#591). The build must discard all of it before Flutter runs.
const GENERATED_STATE = [
  ".dart_tool",
  "build",
  ".flutter-plugins",
  ".flutter-plugins-dependencies",
] as const;

const ICON_NAMES = [
  "Icon-192.png",
  "Icon-512.png",
  "Icon-maskable-192.png",
  "Icon-maskable-512.png",
];

let tempRoot: string | undefined;

afterEach(() => {
  if (tempRoot) rmSync(tempRoot, { recursive: true, force: true });
  tempRoot = undefined;
});

/** Stand up a fixture app with the remnants of a previous release's build. */
function createWarmFixture(root: string): string {
  const appDir = join(root, "flutter_dashboard");
  const registrantDir = join(appDir, ".dart_tool", "flutter_build", "0123456789abcdef");
  mkdirSync(registrantDir, { recursive: true });
  writeFileSync(
    join(registrantDir, "web_plugin_registrant.dart"),
    "// stale: registers only the previous release's plugins\n"
  );
  writeFileSync(join(appDir, ".dart_tool", "package_config.json"), "{}\n");
  mkdirSync(join(appDir, "build", "web"), { recursive: true });
  writeFileSync(join(appDir, "build", "web", "index.html"), "<html>stale</html>\n");
  writeFileSync(join(appDir, ".flutter-plugins"), "connectivity_plus=stale\n");
  writeFileSync(join(appDir, ".flutter-plugins-dependencies"), "{}\n");
  const iconDir = join(appDir, "web", "icons", "prod");
  mkdirSync(iconDir, { recursive: true });
  for (const iconName of ICON_NAMES) writeFileSync(join(iconDir, iconName), "");
  return appDir;
}

/**
 * A stand-in for `flutter build web --release`: records which generated state
 * still exists when Flutter is invoked, then emits the minimal web output the
 * rest of the build script expects.
 */
function createFlutterStub(root: string, observationPath: string): string {
  const stubPath = join(root, "flutter-stub.mjs");
  writeFileSync(
    stubPath,
    [
      'import { existsSync, mkdirSync, writeFileSync } from "node:fs";',
      'import { join } from "node:path";',
      `const generated = ${JSON.stringify(GENERATED_STATE)};`,
      "const present = generated.filter((entry) => existsSync(join(process.cwd(), entry)));",
      `writeFileSync(${JSON.stringify(observationPath)}, JSON.stringify({ args: process.argv.slice(2), present }));`,
      'const webDir = join(process.cwd(), "build", "web");',
      "mkdirSync(webDir, { recursive: true });",
      'writeFileSync(join(webDir, "index.html"), "<html><head><title>x</title></head></html>\\n");',
      'writeFileSync(join(webDir, "manifest.json"), "{}\\n");',
      "",
    ].join("\n")
  );
  return stubPath;
}

describe("build-dashboard-ui.mjs clean context", () => {
  it("discards the previous release's generated Flutter state before invoking flutter", () => {
    tempRoot = mkdtempSync(join(tmpdir(), "rusa-dashboard-build-"));
    const appDir = createWarmFixture(tempRoot);
    const observationPath = join(tempRoot, "flutter-invocation.json");
    const stubPath = createFlutterStub(tempRoot, observationPath);
    const distDir = join(tempRoot, "dist");

    const result = spawnSync(process.execPath, [scriptPath], {
      cwd: tempRoot,
      encoding: "utf8",
      env: {
        ...process.env,
        FLUTTER_CMD: `${process.execPath} ${stubPath}`,
        RUSA_DIST_DIR: distDir,
        RUSA_FLUTTER_APP_DIR: appDir,
      },
    });
    expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0);

    expect(existsSync(observationPath)).toBe(true);
    const observation = JSON.parse(readFileSync(observationPath, "utf8")) as {
      args: string[];
      present: string[];
    };
    expect(observation.args).toEqual(["build", "web", "--release"]);
    // Nothing generated by the previous build may survive into this one.
    expect(observation.present).toEqual([]);

    // The stub's fresh output, not the stale remnant, is what gets staged.
    expect(readFileSync(join(distDir, "dashboard-ui-app", "index.html"), "utf8")).not.toContain(
      "stale"
    );
  });
});
